class Country {
  final String code;
  final String flag;
  final String name;
  final String symbol;
  final String phoneCode;

  Country(
      {required this.code,
      required this.flag,
      required this.name,
      required this.symbol,
      required this.phoneCode});
}

final List<Country> countryList = [
  Country(
      code: "USD",
      flag: "🇺🇸",
      name: "United States Dollar",
      symbol: "\$",
      phoneCode: "+1"),
  Country(
      code: "EUR", flag: "🇪🇺", name: "Euro", symbol: "€", phoneCode: "+44"),
  Country(
      code: "JPY",
      flag: "🇯🇵",
      name: "Japanese Yen",
      symbol: "¥",
      phoneCode: "+81"),
  Country(
      code: "GBP",
      flag: "🇬🇧",
      name: "British Pound Sterling",
      symbol: "£",
      phoneCode: "+44"),
  Country(
      code: "AUD",
      flag: "🇦🇺",
      name: "Australian Dollar",
      symbol: "\$",
      phoneCode: "+61"),
  Country(
      code: "CAD",
      flag: "🇨🇦",
      name: "Canadian Dollar",
      symbol: "\$",
      phoneCode: "+1"),
  Country(
      code: "CHF",
      flag: "🇨🇭",
      name: "Swiss Franc",
      symbol: "Fr",
      phoneCode: "+41"),
  Country(
      code: "CNY",
      flag: "🇨🇳",
      name: "Chinese Yuan",
      symbol: "¥",
      phoneCode: "+86"),
  Country(
      code: "SEK",
      flag: "🇸🇪",
      name: "Swedish Krona",
      symbol: "kr",
      phoneCode: "+46"),
  Country(
      code: "NZD",
      flag: "🇳🇿",
      name: "New Zealand Dollar",
      symbol: "\$",
      phoneCode: "+64"),
  Country(
      code: "AED",
      flag: "🇦🇪",
      name: "United Arab Emirates Dirham",
      symbol: "د.إ",
      phoneCode: "+971"),
  Country(
      code: "AFN",
      flag: "🇦🇫",
      name: "Afghan Afghani",
      symbol: "؋",
      phoneCode: "+93"),
  Country(
      code: "ALL",
      flag: "🇦🇱",
      name: "Albanian Lek",
      symbol: "L",
      phoneCode: "+355"),
  Country(
      code: "AMD",
      flag: "🇦🇲",
      name: "Armenian Dram",
      symbol: "֏",
      phoneCode: "+374"),
  Country(
      code: "ANG",
      flag: "🇳🇱",
      name: "Netherlands Antillean Guilder",
      symbol: "ƒ",
      phoneCode: "+599"),
  Country(
      code: "AOA",
      flag: "🇦🇴",
      name: "Angolan Kwanza",
      symbol: "Kz",
      phoneCode: "+244"),
  Country(
      code: "ARS",
      flag: "🇦🇷",
      name: "Argentine Peso",
      symbol: "\$",
      phoneCode: "+54"),
  Country(
      code: "AWG",
      flag: "🇦🇼",
      name: "Aruban Florin",
      symbol: "ƒ",
      phoneCode: "+297"),
  Country(
      code: "AZN",
      flag: "🇦🇿",
      name: "Azerbaijani Manat",
      symbol: "₼",
      phoneCode: "+994"),
  Country(
      code: "BAM",
      flag: "🇧🇦",
      name: "Bosnia-Herzegovina Convertible Mark",
      symbol: "KM",
      phoneCode: "+387"),
  // Country(
  //     code: "BBD",
  //     flag: "🇧🇧",
  //     name: "Barbadian Dollar",
  //     symbol: "\$",
  //     phoneCode: "+1-246"),
  Country(
      code: "BDT",
      flag: "🇧🇩",
      name: "Bangladeshi Taka",
      symbol: "৳",
      phoneCode: "+880"),
  Country(
      code: "BGN",
      flag: "🇧🇬",
      name: "Bulgarian Lev",
      symbol: "лв",
      phoneCode: "+359"),
  Country(
      code: "BHD",
      flag: "🇧🇭",
      name: "Bahraini Dinar",
      symbol: "ب.د",
      phoneCode: "+973"),
  Country(
      code: "BIF",
      flag: "🇧🇮",
      name: "Burundian Franc",
      symbol: "₣",
      phoneCode: "+257"),
  // Country(
  //     code: "BMD",
  //     flag: "🇧🇲",
  //     name: "Bermudian Dollar",
  //     symbol: "\$",
  //     phoneCode: "+1-441"),
  Country(
      code: "BND",
      flag: "🇧🇳",
      name: "Brunei Dollar",
      symbol: "\$",
      phoneCode: "+673"),
  Country(
      code: "BOB",
      flag: "🇧🇴",
      name: "Bolivian Boliviano",
      symbol: "Bs.",
      phoneCode: "+591"),
  Country(
      code: "BRL",
      flag: "🇧🇷",
      name: "Brazilian Real",
      symbol: "R\$",
      phoneCode: "+55"),
  // Country(
  //     code: "BSD",
  //     flag: "🇧🇸",
  //     name: "Bahamian Dollar",
  //     symbol: "\$",
  //     phoneCode: "+1-242"),
  Country(
      code: "BTN",
      flag: "🇧🇹",
      name: "Bhutanese Ngultrum",
      symbol: "Nu.",
      phoneCode: "+975"),
  Country(
      code: "BWP",
      flag: "🇧🇼",
      name: "Botswana Pula",
      symbol: "P",
      phoneCode: "+267"),
  Country(
      code: "BYN",
      flag: "🇧🇾",
      name: "Belarusian Ruble",
      symbol: "Br",
      phoneCode: "+375"),
  Country(
      code: "BZD",
      flag: "🇧🇿",
      name: "Belize Dollar",
      symbol: "BZ\$",
      phoneCode: "+501"),
  Country(
      code: "CDF",
      flag: "🇨🇩",
      name: "Congolese Franc",
      symbol: "Fr",
      phoneCode: "+243"),
  Country(
      code: "CLP",
      flag: "🇨🇱",
      name: "Chilean Peso",
      symbol: "\$",
      phoneCode: "+56"),
  Country(
      code: "COP",
      flag: "🇨🇴",
      name: "Colombian Peso",
      symbol: "\$",
      phoneCode: "+57"),
  Country(
      code: "CRC",
      flag: "🇨🇷",
      name: "Costa Rican Colón",
      symbol: "₡",
      phoneCode: "+506"),
  Country(
      code: "CUP",
      flag: "🇨🇺",
      name: "Cuban Peso",
      symbol: "₱",
      phoneCode: "+53"),
  Country(
      code: "CVE",
      flag: "🇨🇻",
      name: "Cape Verdean Escudo",
      symbol: "\$",
      phoneCode: "+238"),
  Country(
      code: "CZK",
      flag: "🇨🇿",
      name: "Czech Koruna",
      symbol: "Kč",
      phoneCode: "+420"),
  Country(
      code: "DJF",
      flag: "🇩🇯",
      name: "Djiboutian Franc",
      symbol: "Fdj",
      phoneCode: "+253"),
  Country(
      code: "DKK",
      flag: "🇩🇰",
      name: "Danish Krone",
      symbol: "kr",
      phoneCode: "+45"),
  // Country(
  //     code: "DOP",
  //     flag: "🇩🇴",
  //     name: "Dominican Peso",
  //     symbol: "RD\$",
  //     phoneCode: "+1-809"),
  Country(
      code: "DZD",
      flag: "🇩🇿",
      name: "Algerian Dinar",
      symbol: "د.ج",
      phoneCode: "+213"),
  Country(
      code: "EGP",
      flag: "🇪🇬",
      name: "Egyptian Pound",
      symbol: "ج.م",
      phoneCode: "+20"),
  Country(
      code: "ERN",
      flag: "🇪🇷",
      name: "Eritrean Nakfa",
      symbol: "Nfk",
      phoneCode: "+291"),
  Country(
      code: "ETB",
      flag: "🇪🇹",
      name: "Ethiopian Birr",
      symbol: "Br",
      phoneCode: "+251"),
  Country(
      code: "FJD",
      flag: "🇫🇯",
      name: "Fijian Dollar",
      symbol: "\$",
      phoneCode: "+679"),
  Country(
      code: "FKP",
      flag: "🇫🇰",
      name: "Falkland Islands Pound",
      symbol: "£",
      phoneCode: "+500"),
  Country(
      code: "FOK",
      flag: "🇫🇴",
      name: "Faroese Króna",
      symbol: "kr",
      phoneCode: "+298"),
  Country(
      code: "GEL",
      flag: "🇬🇪",
      name: "Georgian Lari",
      symbol: "₾",
      phoneCode: "+995"),
  // Country(
  //     code: "GGP",
  //     flag: "🇬🇬",
  //     name: "Guernsey Pound",
  //     symbol: "£",
  //     phoneCode: "+44-1481"),
  Country(
      code: "GHS",
      flag: "🇬🇭",
      name: "Ghanaian Cedi",
      symbol: "₵",
      phoneCode: "+233"),
  Country(
      code: "GIP",
      flag: "🇬🇮",
      name: "Gibraltar Pound",
      symbol: "£",
      phoneCode: "+350"),
  Country(
      code: "GMD",
      flag: "🇬🇲",
      name: "Gambian Dalasi",
      symbol: "D",
      phoneCode: "+220"),
  Country(
      code: "GNF",
      flag: "🇬🇳",
      name: "Guinean Franc",
      symbol: "Fr",
      phoneCode: "+224"),
  Country(
      code: "GTQ",
      flag: "🇬🇹",
      name: "Guatemalan Quetzal",
      symbol: "Q",
      phoneCode: "+502"),
  Country(
      code: "GYD",
      flag: "🇬🇾",
      name: "Guyanese Dollar",
      symbol: "\$",
      phoneCode: "+592"),
  Country(
      code: "HKD",
      flag: "🇭🇰",
      name: "Hong Kong Dollar",
      symbol: "\$",
      phoneCode: "+852"),
  Country(
      code: "HNL",
      flag: "🇭🇳",
      name: "Honduran Lempira",
      symbol: "L",
      phoneCode: "+504"),
  Country(
      code: "HRK",
      flag: "🇭🇷",
      name: "Croatian Kuna",
      symbol: "kn",
      phoneCode: "+385"),
  Country(
      code: "HTG",
      flag: "🇭🇹",
      name: "Haitian Gourde",
      symbol: "G",
      phoneCode: "+509"),
  Country(
      code: "HUF",
      flag: "🇭🇺",
      name: "Hungarian Forint",
      symbol: "Ft",
      phoneCode: "+36"),
  Country(
      code: "IDR",
      flag: "🇮🇩",
      name: "Indonesian Rupiah",
      symbol: "Rp",
      phoneCode: "+62"),
  Country(
      code: "ILS",
      flag: "🇮🇱",
      name: "Israeli New Shekel",
      symbol: "₪",
      phoneCode: "+972"),
  // Country(
  //     code: "IMP",
  //     flag: "🇮🇲",
  //     name: "Isle of Man Pound",
  //     symbol: "£",
  //     phoneCode: "+44-1624"),
  Country(
      code: "INR",
      flag: "🇮🇳",
      name: "Indian Rupee",
      symbol: "₹",
      phoneCode: "+91"),
  Country(
      code: "IQD",
      flag: "🇮🇶",
      name: "Iraqi Dinar",
      symbol: "ع.د",
      phoneCode: "+964"),
  Country(
      code: "IRR",
      flag: "🇮🇷",
      name: "Iranian Rial",
      symbol: "﷼",
      phoneCode: "+98"),
  Country(
      code: "ISK",
      flag: "🇮🇸",
      name: "Icelandic Króna",
      symbol: "kr",
      phoneCode: "+354"),
  // Country(
  //     code: "JEP",
  //     flag: "🇯🇪",
  //     name: "Jersey Pound",
  //     symbol: "£",
  //     phoneCode: "+44-1534"),
  // Country(
  //     code: "JMD",
  //     flag: "🇯🇲",
  //     name: "Jamaican Dollar",
  //     symbol: "\$",
  //     phoneCode: "+1-876"),
  Country(
      code: "JOD",
      flag: "🇯🇴",
      name: "Jordanian Dinar",
      symbol: "د.ا",
      phoneCode: "+962"),
  Country(
      code: "KES",
      flag: "🇰🇪",
      name: "Kenyan Shilling",
      symbol: "KSh",
      phoneCode: "+254"),
  Country(
      code: "KGS",
      flag: "🇰🇬",
      name: "Kyrgyzstani Som",
      symbol: "с",
      phoneCode: "+996"),
  Country(
      code: "KHR",
      flag: "🇰🇭",
      name: "Cambodian Riel",
      symbol: "៛",
      phoneCode: "+855"),
  Country(
      code: "KID",
      flag: "🇰🇮",
      name: "Kiribati Dollar",
      symbol: "\$",
      phoneCode: "+686"),
  Country(
      code: "KMF",
      flag: "🇰🇲",
      name: "Comorian Franc",
      symbol: "Fr",
      phoneCode: "+269"),
  Country(
      code: "KRW",
      flag: "🇰🇷",
      name: "South Korean Won",
      symbol: "₩",
      phoneCode: "+82"),
  Country(
      code: "KWD",
      flag: "🇰🇼",
      name: "Kuwaiti Dinar",
      symbol: "د.ك",
      phoneCode: "+965"),
  // Country(
  //     code: "KYD",
  //     flag: "🇰🇾",
  //     name: "Cayman Islands Dollar",
  //     symbol: "\$",
  //     phoneCode: "+1-345"),
  Country(
      code: "KZT",
      flag: "🇰🇿",
      name: "Kazakhstani Tenge",
      symbol: "₸",
      phoneCode: "+7"),
  Country(
      code: "LAK",
      flag: "🇱🇦",
      name: "Lao Kip",
      symbol: "₭",
      phoneCode: "+856"),
  Country(
      code: "LBP",
      flag: "🇱🇧",
      name: "Lebanese Pound",
      symbol: "ل.ل",
      phoneCode: "+961"),
  Country(
      code: "LKR",
      flag: "🇱🇰",
      name: "Sri Lankan Rupee",
      symbol: "රු",
      phoneCode: "+94"),
  Country(
      code: "LRD",
      flag: "🇱🇷",
      name: "Liberian Dollar",
      symbol: "\$",
      phoneCode: "+231"),
  Country(
      code: "LSL",
      flag: "🇱🇸",
      name: "Lesotho Loti",
      symbol: "L",
      phoneCode: "+266"),
  Country(
      code: "LYD",
      flag: "🇱🇾",
      name: "Libyan Dinar",
      symbol: "ل.د",
      phoneCode: "+218"),
  Country(
      code: "MAD",
      flag: "🇲🇦",
      name: "Moroccan Dirham",
      symbol: "د.م",
      phoneCode: "+212"),
  Country(
      code: "MDL",
      flag: "🇲🇩",
      name: "Moldovan Leu",
      symbol: "L",
      phoneCode: "+373"),
  Country(
      code: "MGA",
      flag: "🇲🇬",
      name: "Malagasy Ariary",
      symbol: "Ar",
      phoneCode: "+261"),
  Country(
      code: "MKD",
      flag: "🇲🇰",
      name: "Macedonian Denar",
      symbol: "ден",
      phoneCode: "+389"),
  Country(
      code: "MMK",
      flag: "🇲🇲",
      name: "Burmese Kyat",
      symbol: "Ks",
      phoneCode: "+95"),
  Country(
      code: "MNT",
      flag: "🇲🇳",
      name: "Mongolian Tögrög",
      symbol: "₮",
      phoneCode: "+976"),
  Country(
      code: "MOP",
      flag: "🇲🇴",
      name: "Macanese Pataca",
      symbol: "P",
      phoneCode: "+853"),
  Country(
      code: "MRU",
      flag: "🇲🇷",
      name: "Mauritanian Ouguiya",
      symbol: "UM",
      phoneCode: "+222"),
  Country(
      code: "MUR",
      flag: "🇲🇺",
      name: "Mauritian Rupee",
      symbol: "₨",
      phoneCode: "+230"),
  Country(
      code: "MVR",
      flag: "🇲🇻",
      name: "Maldivian Rufiyaa",
      symbol: "ރ.",
      phoneCode: "+960"),
  Country(
      code: "MWK",
      flag: "🇲🇼",
      name: "Malawian Kwacha",
      symbol: "MK",
      phoneCode: "+265"),
  Country(
      code: "MXN",
      flag: "🇲🇽",
      name: "Mexican Peso",
      symbol: "\$",
      phoneCode: "+52"),
  Country(
      code: "MYR",
      flag: "🇲🇾",
      name: "Malaysian Ringgit",
      symbol: "RM",
      phoneCode: "+60"),
  Country(
      code: "MZN",
      flag: "🇲🇿",
      name: "Mozambican Metical",
      symbol: "MT",
      phoneCode: "+258"),
  Country(
      code: "NAD",
      flag: "🇳🇦",
      name: "Namibian Dollar",
      symbol: "\$",
      phoneCode: "+264"),
  Country(
      code: "NGN",
      flag: "🇳🇬",
      name: "Nigerian Naira",
      symbol: "₦",
      phoneCode: "+234"),
  Country(
      code: "NIO",
      flag: "🇳🇮",
      name: "Nicaraguan Córdoba",
      symbol: "C\$",
      phoneCode: "+505"),
  Country(
      code: "NOK",
      flag: "🇳🇴",
      name: "Norwegian Krone",
      symbol: "kr",
      phoneCode: "+47"),
  Country(
      code: "NPR",
      flag: "🇳🇵",
      name: "Nepalese Rupee",
      symbol: "₨",
      phoneCode: "+977"),
  Country(
      code: "OMR",
      flag: "🇴🇲",
      name: "Omani Rial",
      symbol: "ر.ع.",
      phoneCode: "+968"),
  Country(
      code: "PAB",
      flag: "🇵🇦",
      name: "Panamanian Balboa",
      symbol: "B/.",
      phoneCode: "+507"),
  Country(
      code: "PEN",
      flag: "🇵🇪",
      name: "Peruvian Sol",
      symbol: "S/.",
      phoneCode: "+51"),
  Country(
      code: "PGK",
      flag: "🇵🇬",
      name: "Papua New Guinean Kina",
      symbol: "K",
      phoneCode: "+675"),
  Country(
      code: "PHP",
      flag: "🇵🇭",
      name: "Philippine Peso",
      symbol: "₱",
      phoneCode: "+63"),
  Country(
      code: "PKR",
      flag: "🇵🇰",
      name: "Pakistani Rupee",
      symbol: "₨",
      phoneCode: "+92"),
  Country(
      code: "PLN",
      flag: "🇵🇱",
      name: "Polish Złoty",
      symbol: "zł",
      phoneCode: "+48"),
  Country(
      code: "PYG",
      flag: "🇵🇾",
      name: "Paraguayan Guaraní",
      symbol: "₲",
      phoneCode: "+595"),
  Country(
      code: "QAR",
      flag: "🇶🇦",
      name: "Qatari Riyal",
      symbol: "ر.ق",
      phoneCode: "+974"),
  Country(
      code: "RON",
      flag: "🇷🇴",
      name: "Romanian Leu",
      symbol: "lei",
      phoneCode: "+40"),
  Country(
      code: "RSD",
      flag: "🇷🇸",
      name: "Serbian Dinar",
      symbol: "дин.",
      phoneCode: "+381"),
  Country(
      code: "RUB",
      flag: "🇷🇺",
      name: "Russian Ruble",
      symbol: "₽",
      phoneCode: "+7"),
  Country(
      code: "RWF",
      flag: "🇷🇼",
      name: "Rwandan Franc",
      symbol: "Fr",
      phoneCode: "+250"),
  Country(
      code: "SAR",
      flag: "🇸🇦",
      name: "Saudi Riyal",
      symbol: "ر.س",
      phoneCode: "+966"),
  Country(
      code: "SBD",
      flag: "🇸🇧",
      name: "Solomon Islands Dollar",
      symbol: "\$",
      phoneCode: "+677"),
  Country(
      code: "SCR",
      flag: "🇸🇨",
      name: "Seychellois Rupee",
      symbol: "₨",
      phoneCode: "+248"),
  Country(
      code: "SDG",
      flag: "🇸🇩",
      name: "Sudanese Pound",
      symbol: "ج.س",
      phoneCode: "+249"),
  Country(
      code: "SGD",
      flag: "🇸🇬",
      name: "Singapore Dollar",
      symbol: "\$",
      phoneCode: "+65"),
  Country(
      code: "SHP",
      flag: "🇸🇭",
      name: "Saint Helena Pound",
      symbol: "£",
      phoneCode: "+290"),
  Country(
      code: "SLL",
      flag: "🇸🇱",
      name: "Sierra Leonean Leone",
      symbol: "Le",
      phoneCode: "+232"),
  Country(
      code: "SOS",
      flag: "🇸🇴",
      name: "Somali Shilling",
      symbol: "Sh",
      phoneCode: "+252"),
  Country(
      code: "SRD",
      flag: "🇸🇷",
      name: "Surinamese Dollar",
      symbol: "\$",
      phoneCode: "+597"),
  Country(
      code: "SSP",
      flag: "🇸🇸",
      name: "South Sudanese Pound",
      symbol: "£",
      phoneCode: "+211"),
  Country(
      code: "STN",
      flag: "🇸🇹",
      name: "São Tomé and Príncipe Dobra",
      symbol: "Db",
      phoneCode: "+239"),
  Country(
      code: "SYP",
      flag: "🇸🇾",
      name: "Syrian Pound",
      symbol: "£S",
      phoneCode: "+963"),
  Country(
      code: "SZL",
      flag: "🇸🇿",
      name: "Eswatini Lilangeni",
      symbol: "E",
      phoneCode: "+268"),
  Country(
      code: "THB",
      flag: "🇹🇭",
      name: "Thai Baht",
      symbol: "฿",
      phoneCode: "+66"),
  Country(
      code: "TJS",
      flag: "🇹🇯",
      name: "Tajikistani Somoni",
      symbol: "ЅМ",
      phoneCode: "+992"),
  Country(
      code: "TMT",
      flag: "🇹🇲",
      name: "Turkmenistani Manat",
      symbol: "m",
      phoneCode: "+993"),
  Country(
      code: "TND",
      flag: "🇹🇳",
      name: "Tunisian Dinar",
      symbol: "د.ت",
      phoneCode: "+216"),
  Country(
      code: "TOP",
      flag: "🇹🇴",
      name: "Tongan Paʻanga",
      symbol: "T\$",
      phoneCode: "+676"),
  Country(
      code: "TRY",
      flag: "🇹🇷",
      name: "Turkish Lira",
      symbol: "₺",
      phoneCode: "+90"),
  // Country(
  //     code: "TTD",
  //     flag: "🇹🇹",
  //     name: "Trinidad and Tobago Dollar",
  //     symbol: "TT\$",
  //     phoneCode: "+1-868"),
  Country(
      code: "TVD",
      flag: "🇹🇻",
      name: "Tuvaluan Dollar",
      symbol: "\$",
      phoneCode: "+688"),
  Country(
      code: "TZS",
      flag: "🇹🇿",
      name: "Tanzanian Shilling",
      symbol: "TSh",
      phoneCode: "+255"),
  Country(
      code: "UAH",
      flag: "🇺🇦",
      name: "Ukrainian Hryvnia",
      symbol: "₴",
      phoneCode: "+380"),
  Country(
      code: "UGX",
      flag: "🇺🇬",
      name: "Ugandan Shilling",
      symbol: "USh",
      phoneCode: "+256"),
  Country(
      code: "UYU",
      flag: "🇺🇾",
      name: "Uruguayan Peso",
      symbol: "\$U",
      phoneCode: "+598"),
  Country(
      code: "UZS",
      flag: "🇺🇿",
      name: "Uzbekistani Soʻm",
      symbol: "лв",
      phoneCode: "+998"),
  Country(
      code: "VES",
      flag: "🇻🇪",
      name: "Venezuelan Bolívar",
      symbol: "Bs.",
      phoneCode: "+58"),
  Country(
      code: "VND",
      flag: "🇻🇳",
      name: "Vietnamese Đồng",
      symbol: "₫",
      phoneCode: "+84"),
  Country(
      code: "VUV",
      flag: "🇻🇺",
      name: "Vanuatu Vatu",
      symbol: "VT",
      phoneCode: "+678"),
  Country(
      code: "WST",
      flag: "🇼🇸",
      name: "Samoan Tālā",
      symbol: "T",
      phoneCode: "+685"),
  Country(
      code: "XAF",
      flag: "🇨🇲",
      name: "Central African CFA Franc",
      symbol: "FCFA",
      phoneCode: "+237"),
  // Country(
  //     code: "XCD",
  //     flag: "🇦🇬",
  //     name: "East Caribbean Dollar",
  //     symbol: "\$",
  //     phoneCode: "+1-268"),
  Country(
      code: "XOF",
      flag: "🇧🇯",
      name: "West African CFA Franc",
      symbol: "CFA",
      phoneCode: "+229"),
  Country(
      code: "XPF",
      flag: "🇵🇫",
      name: "CFP Franc",
      symbol: "₣",
      phoneCode: "+689"),
  Country(
      code: "YER",
      flag: "🇾🇪",
      name: "Yemeni Rial",
      symbol: "﷼",
      phoneCode: "+967"),
  Country(
      code: "ZAR",
      flag: "🇿🇦",
      name: "South African Rand",
      symbol: "R",
      phoneCode: "+27"),
  Country(
      code: "ZMW",
      flag: "🇿🇲",
      name: "Zambian Kwacha",
      symbol: "ZK",
      phoneCode: "+260"),
  Country(
      code: "ZWL",
      flag: "🇿🇼",
      name: "Zimbabwean Dollar",
      symbol: "\$",
      phoneCode: "+263"),
];
