class Currency {
  final String code;
  final String flag;
  final String name;
  final String symbol;

  Currency({
    required this.code,
    required this.flag,
    required this.name,
    required this.symbol,
  });
}

final List<Currency> currencyList = [
  Currency(
      code: "USD", flag: "🇺🇸", name: "United States Dollar", symbol: "\$"),
  Currency(code: "EUR", flag: "🇪🇺", name: "Euro", symbol: "€"),
  Currency(code: "JPY", flag: "🇯🇵", name: "Japanese Yen", symbol: "¥"),
  Currency(
      code: "GBP", flag: "🇬🇧", name: "British Pound Sterling", symbol: "£"),
  Currency(code: "AUD", flag: "🇦🇺", name: "Australian Dollar", symbol: "\$"),
  Currency(code: "CAD", flag: "🇨🇦", name: "Canadian Dollar", symbol: "\$"),
  Currency(code: "CHF", flag: "🇨🇭", name: "Swiss Franc", symbol: "Fr"),
  Currency(code: "CNY", flag: "🇨🇳", name: "Chinese Yuan", symbol: "¥"),
  Currency(code: "SEK", flag: "🇸🇪", name: "Swedish Krona", symbol: "kr"),
  Currency(code: "NZD", flag: "🇳🇿", name: "New Zealand Dollar", symbol: "\$"),
  Currency(
      code: "AED",
      flag: "🇦🇪",
      name: "United Arab Emirates Dirham",
      symbol: "د.إ"),
  Currency(code: "AFN", flag: "🇦🇫", name: "Afghan Afghani", symbol: "؋"),
  Currency(code: "ALL", flag: "🇦🇱", name: "Albanian Lek", symbol: "L"),
  Currency(code: "AMD", flag: "🇦🇲", name: "Armenian Dram", symbol: "֏"),
  Currency(
      code: "ANG",
      flag: "🇳🇱",
      name: "Netherlands Antillean Guilder",
      symbol: "ƒ"),
  Currency(code: "AOA", flag: "🇦🇴", name: "Angolan Kwanza", symbol: "Kz"),
  Currency(code: "ARS", flag: "🇦🇷", name: "Argentine Peso", symbol: "\$"),
  Currency(code: "AWG", flag: "🇦🇼", name: "Aruban Florin", symbol: "ƒ"),
  Currency(code: "AZN", flag: "🇦🇿", name: "Azerbaijani Manat", symbol: "₼"),
  Currency(
      code: "BAM",
      flag: "🇧🇦",
      name: "Bosnia-Herzegovina Convertible Mark",
      symbol: "KM"),
  Currency(code: "BBD", flag: "🇧🇧", name: "Barbadian Dollar", symbol: "\$"),
  Currency(code: "BDT", flag: "🇧🇩", name: "Bangladeshi Taka", symbol: "৳"),
  Currency(code: "BGN", flag: "🇧🇬", name: "Bulgarian Lev", symbol: "лв"),
  Currency(code: "BHD", flag: "🇧🇭", name: "Bahraini Dinar", symbol: "ب.د"),
  Currency(code: "BIF", flag: "🇧🇮", name: "Burundian Franc", symbol: "₣"),
  Currency(code: "BMD", flag: "🇧🇲", name: "Bermudian Dollar", symbol: "\$"),
  Currency(code: "BND", flag: "🇧🇳", name: "Brunei Dollar", symbol: "\$"),
  Currency(
      code: "BOB", flag: "🇧🇴", name: "Bolivian Boliviano", symbol: "Bs."),
  Currency(code: "BRL", flag: "🇧🇷", name: "Brazilian Real", symbol: "R\$"),
  Currency(code: "BSD", flag: "🇧🇸", name: "Bahamian Dollar", symbol: "\$"),
  Currency(
      code: "BTN", flag: "🇧🇹", name: "Bhutanese Ngultrum", symbol: "Nu."),
  Currency(code: "BWP", flag: "🇧🇼", name: "Botswana Pula", symbol: "P"),
  Currency(code: "BYN", flag: "🇧🇾", name: "Belarusian Ruble", symbol: "Br"),
  Currency(code: "BZD", flag: "🇧🇿", name: "Belize Dollar", symbol: "BZ\$"),
  Currency(code: "CDF", flag: "🇨🇩", name: "Congolese Franc", symbol: "Fr"),
  Currency(code: "CLP", flag: "🇨🇱", name: "Chilean Peso", symbol: "\$"),
  Currency(code: "COP", flag: "🇨🇴", name: "Colombian Peso", symbol: "\$"),
  Currency(code: "CRC", flag: "🇨🇷", name: "Costa Rican Colón", symbol: "₡"),
  Currency(code: "CUP", flag: "🇨🇺", name: "Cuban Peso", symbol: "₱"),
  Currency(
      code: "CVE", flag: "🇨🇻", name: "Cape Verdean Escudo", symbol: "\$"),
  Currency(code: "CZK", flag: "🇨🇿", name: "Czech Koruna", symbol: "Kč"),
  Currency(code: "DJF", flag: "🇩🇯", name: "Djiboutian Franc", symbol: "Fdj"),
  Currency(code: "DKK", flag: "🇩🇰", name: "Danish Krone", symbol: "kr"),
  Currency(code: "DOP", flag: "🇩🇴", name: "Dominican Peso", symbol: "RD\$"),
  Currency(code: "DZD", flag: "🇩🇿", name: "Algerian Dinar", symbol: "د.ج"),
  Currency(code: "EGP", flag: "🇪🇬", name: "Egyptian Pound", symbol: "ج.م"),
  Currency(code: "ERN", flag: "🇪🇷", name: "Eritrean Nakfa", symbol: "Nfk"),
  Currency(code: "ETB", flag: "🇪🇹", name: "Ethiopian Birr", symbol: "Br"),
  Currency(code: "FJD", flag: "🇫🇯", name: "Fijian Dollar", symbol: "\$"),
  Currency(
      code: "FKP", flag: "🇫🇰", name: "Falkland Islands Pound", symbol: "£"),
  Currency(code: "FOK", flag: "🇫🇴", name: "Faroese Króna", symbol: "kr"),
  Currency(code: "GEL", flag: "🇬🇪", name: "Georgian Lari", symbol: "₾"),
  Currency(code: "GGP", flag: "🇬🇬", name: "Guernsey Pound", symbol: "£"),
  Currency(code: "GHS", flag: "🇬🇭", name: "Ghanaian Cedi", symbol: "₵"),
  Currency(code: "GIP", flag: "🇬🇮", name: "Gibraltar Pound", symbol: "£"),
  Currency(code: "GMD", flag: "🇬🇲", name: "Gambian Dalasi", symbol: "D"),
  Currency(code: "GNF", flag: "🇬🇳", name: "Guinean Franc", symbol: "Fr"),
  Currency(code: "GTQ", flag: "🇬🇹", name: "Guatemalan Quetzal", symbol: "Q"),
  Currency(code: "GYD", flag: "🇬🇾", name: "Guyanese Dollar", symbol: "\$"),
  Currency(code: "HKD", flag: "🇭🇰", name: "Hong Kong Dollar", symbol: "\$"),
  Currency(code: "HNL", flag: "🇭🇳", name: "Honduran Lempira", symbol: "L"),
  Currency(code: "HRK", flag: "🇭🇷", name: "Croatian Kuna", symbol: "kn"),
  Currency(code: "HTG", flag: "🇭🇹", name: "Haitian Gourde", symbol: "G"),
  Currency(code: "HUF", flag: "🇭🇺", name: "Hungarian Forint", symbol: "Ft"),
  Currency(code: "IDR", flag: "🇮🇩", name: "Indonesian Rupiah", symbol: "Rp"),
  Currency(code: "ILS", flag: "🇮🇱", name: "Israeli New Shekel", symbol: "₪"),
  Currency(code: "IMP", flag: "🇮🇲", name: "Isle of Man Pound", symbol: "£"),
  Currency(code: "INR", flag: "🇮🇳", name: "Indian Rupee", symbol: "₹"),
  Currency(code: "IQD", flag: "🇮🇶", name: "Iraqi Dinar", symbol: "ع.د"),
  Currency(code: "IRR", flag: "🇮🇷", name: "Iranian Rial", symbol: "﷼"),
  Currency(code: "ISK", flag: "🇮🇸", name: "Icelandic Króna", symbol: "kr"),
  Currency(code: "JEP", flag: "🇯🇪", name: "Jersey Pound", symbol: "£"),
  Currency(code: "JMD", flag: "🇯🇲", name: "Jamaican Dollar", symbol: "\$"),
  Currency(code: "JOD", flag: "🇯🇴", name: "Jordanian Dinar", symbol: "د.ا"),
  Currency(code: "KES", flag: "🇰🇪", name: "Kenyan Shilling", symbol: "KSh"),
  Currency(code: "KGS", flag: "🇰🇬", name: "Kyrgyzstani Som", symbol: "с"),
  Currency(code: "KHR", flag: "🇰🇭", name: "Cambodian Riel", symbol: "៛"),
  Currency(code: "KID", flag: "🇰🇮", name: "Kiribati Dollar", symbol: "\$"),
  Currency(code: "KMF", flag: "🇰🇲", name: "Comorian Franc", symbol: "Fr"),
  Currency(code: "KRW", flag: "🇰🇷", name: "South Korean Won", symbol: "₩"),
  Currency(code: "KWD", flag: "🇰🇼", name: "Kuwaiti Dinar", symbol: "د.ك"),
  Currency(
      code: "KYD", flag: "🇰🇾", name: "Cayman Islands Dollar", symbol: "\$"),
  Currency(code: "KZT", flag: "🇰🇿", name: "Kazakhstani Tenge", symbol: "₸"),
  Currency(code: "LAK", flag: "🇱🇦", name: "Lao Kip", symbol: "₭"),
  Currency(code: "LBP", flag: "🇱🇧", name: "Lebanese Pound", symbol: "ل.ل"),
  Currency(code: "LKR", flag: "🇱🇰", name: "Sri Lankan Rupee", symbol: "රු"),
  Currency(code: "LRD", flag: "🇱🇷", name: "Liberian Dollar", symbol: "\$"),
  Currency(code: "LSL", flag: "🇱🇸", name: "Lesotho Loti", symbol: "L"),
  Currency(code: "LYD", flag: "🇱🇾", name: "Libyan Dinar", symbol: "ل.د"),
  Currency(code: "MAD", flag: "🇲🇦", name: "Moroccan Dirham", symbol: "د.م"),
  Currency(code: "MDL", flag: "🇲🇩", name: "Moldovan Leu", symbol: "L"),
  Currency(code: "MGA", flag: "🇲🇬", name: "Malagasy Ariary", symbol: "Ar"),
  Currency(code: "MKD", flag: "🇲🇰", name: "Macedonian Denar", symbol: "ден"),
  Currency(code: "MMK", flag: "🇲🇲", name: "Burmese Kyat", symbol: "Ks"),
  Currency(code: "MNT", flag: "🇲🇳", name: "Mongolian Tögrög", symbol: "₮"),
  Currency(code: "MOP", flag: "🇲🇴", name: "Macanese Pataca", symbol: "P"),
  Currency(
      code: "MRU", flag: "🇲🇷", name: "Mauritanian Ouguiya", symbol: "UM"),
  Currency(code: "MUR", flag: "🇲🇺", name: "Mauritian Rupee", symbol: "₨"),
  Currency(code: "MVR", flag: "🇲🇻", name: "Maldivian Rufiyaa", symbol: "ރ."),
  Currency(code: "MWK", flag: "🇲🇼", name: "Malawian Kwacha", symbol: "MK"),
  Currency(code: "MXN", flag: "🇲🇽", name: "Mexican Peso", symbol: "\$"),
  Currency(code: "MYR", flag: "🇲🇾", name: "Malaysian Ringgit", symbol: "RM"),
  Currency(code: "MZN", flag: "🇲🇿", name: "Mozambican Metical", symbol: "MT"),
  Currency(code: "NAD", flag: "🇳🇦", name: "Namibian Dollar", symbol: "\$"),
  Currency(code: "NGN", flag: "🇳🇬", name: "Nigerian Naira", symbol: "₦"),
  Currency(
      code: "NIO", flag: "🇳🇮", name: "Nicaraguan Córdoba", symbol: "C\$"),
  Currency(code: "NOK", flag: "🇳🇴", name: "Norwegian Krone", symbol: "kr"),
  Currency(code: "NPR", flag: "🇳🇵", name: "Nepalese Rupee", symbol: "₨"),
  Currency(code: "OMR", flag: "🇴🇲", name: "Omani Rial", symbol: "ر.ع."),
  Currency(code: "PAB", flag: "🇵🇦", name: "Panamanian Balboa", symbol: "B/."),
  Currency(code: "PEN", flag: "🇵🇪", name: "Peruvian Sol", symbol: "S/."),
  Currency(
      code: "PGK", flag: "🇵🇬", name: "Papua New Guinean Kina", symbol: "K"),
  Currency(code: "PHP", flag: "🇵🇭", name: "Philippine Peso", symbol: "₱"),
  Currency(code: "PKR", flag: "🇵🇰", name: "Pakistani Rupee", symbol: "₨"),
  Currency(code: "PLN", flag: "🇵🇱", name: "Polish Złoty", symbol: "zł"),
  Currency(code: "PYG", flag: "🇵🇾", name: "Paraguayan Guaraní", symbol: "₲"),
  Currency(code: "QAR", flag: "🇶🇦", name: "Qatari Riyal", symbol: "ر.ق"),
  Currency(code: "RON", flag: "🇷🇴", name: "Romanian Leu", symbol: "lei"),
  Currency(code: "RSD", flag: "🇷🇸", name: "Serbian Dinar", symbol: "дин."),
  Currency(code: "RUB", flag: "🇷🇺", name: "Russian Ruble", symbol: "₽"),
  Currency(code: "RWF", flag: "🇷🇼", name: "Rwandan Franc", symbol: "Fr"),
  Currency(code: "SAR", flag: "🇸🇦", name: "Saudi Riyal", symbol: "ر.س"),
  Currency(
      code: "SBD", flag: "🇸🇧", name: "Solomon Islands Dollar", symbol: "\$"),
  Currency(code: "SCR", flag: "🇸🇨", name: "Seychellois Rupee", symbol: "₨"),
  Currency(code: "SDG", flag: "🇸🇩", name: "Sudanese Pound", symbol: "ج.س"),
  Currency(code: "SGD", flag: "🇸🇬", name: "Singapore Dollar", symbol: "\$"),
  Currency(code: "SHP", flag: "🇸🇭", name: "Saint Helena Pound", symbol: "£"),
  Currency(
      code: "SLL", flag: "🇸🇱", name: "Sierra Leonean Leone", symbol: "Le"),
  Currency(code: "SOS", flag: "🇸🇴", name: "Somali Shilling", symbol: "Sh"),
  Currency(code: "SRD", flag: "🇸🇷", name: "Surinamese Dollar", symbol: "\$"),
  Currency(
      code: "SSP", flag: "🇸🇸", name: "South Sudanese Pound", symbol: "£"),
  Currency(
      code: "STN",
      flag: "🇸🇹",
      name: "São Tomé and Príncipe Dobra",
      symbol: "Db"),
  Currency(code: "SYP", flag: "🇸🇾", name: "Syrian Pound", symbol: "£S"),
  Currency(code: "SZL", flag: "🇸🇿", name: "Eswatini Lilangeni", symbol: "E"),
  Currency(code: "THB", flag: "🇹🇭", name: "Thai Baht", symbol: "฿"),
  Currency(code: "TJS", flag: "🇹🇯", name: "Tajikistani Somoni", symbol: "ЅМ"),
  Currency(code: "TMT", flag: "🇹🇲", name: "Turkmenistani Manat", symbol: "m"),
  Currency(code: "TND", flag: "🇹🇳", name: "Tunisian Dinar", symbol: "د.ت"),
  Currency(code: "TOP", flag: "🇹🇴", name: "Tongan Paʻanga", symbol: "T\$"),
  Currency(code: "TRY", flag: "🇹🇷", name: "Turkish Lira", symbol: "₺"),
  Currency(
      code: "TTD",
      flag: "🇹🇹",
      name: "Trinidad and Tobago Dollar",
      symbol: "TT\$"),
  Currency(code: "TVD", flag: "🇹🇻", name: "Tuvaluan Dollar", symbol: "\$"),
  Currency(
      code: "TZS", flag: "🇹🇿", name: "Tanzanian Shilling", symbol: "TSh"),
  Currency(code: "UAH", flag: "🇺🇦", name: "Ukrainian Hryvnia", symbol: "₴"),
  Currency(code: "UGX", flag: "🇺🇬", name: "Ugandan Shilling", symbol: "USh"),
  Currency(code: "UYU", flag: "🇺🇾", name: "Uruguayan Peso", symbol: "\$U"),
  Currency(code: "UZS", flag: "🇺🇿", name: "Uzbekistani Soʻm", symbol: "лв"),
  Currency(
      code: "VES", flag: "🇻🇪", name: "Venezuelan Bolívar", symbol: "Bs."),
  Currency(code: "VND", flag: "🇻🇳", name: "Vietnamese Đồng", symbol: "₫"),
  Currency(code: "VUV", flag: "🇻🇺", name: "Vanuatu Vatu", symbol: "VT"),
  Currency(code: "WST", flag: "🇼🇸", name: "Samoan Tālā", symbol: "T"),
  Currency(
      code: "XAF",
      flag: "🇨🇲",
      name: "Central African CFA Franc",
      symbol: "FCFA"),
  Currency(
      code: "XCD", flag: "🇦🇬", name: "East Caribbean Dollar", symbol: "\$"),
  Currency(
      code: "XOF", flag: "🇧🇯", name: "West African CFA Franc", symbol: "CFA"),
  Currency(code: "XPF", flag: "🇵🇫", name: "CFP Franc", symbol: "₣"),
  Currency(code: "YER", flag: "🇾🇪", name: "Yemeni Rial", symbol: "﷼"),
  Currency(code: "ZAR", flag: "🇿🇦", name: "South African Rand", symbol: "R"),
  Currency(code: "ZMW", flag: "🇿🇲", name: "Zambian Kwacha", symbol: "ZK"),
  Currency(code: "ZWL", flag: "🇿🇼", name: "Zimbabwean Dollar", symbol: "\$"),
];
